--Q1. What is the total revenue generated by male vs. female customers?
SELECT 
gender, 
SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (
    SELECT AVG(purchase_amount) 
    FROM customer)

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT 
shipping_type,
AVG(purchase_amount) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
AVG(purchase_amount) AS avg_spend,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
item_purchased,
    CAST(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1
        ELSE 0
    END) / COUNT(*)
    AS DECIMAL (5,2)
  ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH customer_segments AS (
SELECT customer_id, previous_purchases,
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
        END AS customer_segment
    FROM customer
    )

SELECT customer_segment,
COUNT(*) AS customer_count
FROM customer_segments
GROUP BY customer_segment
ORDER BY customer_count DESC;

--Q8. What are the top 3 most purchased products within each category? 

WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS product_rank
    FROM customer
    GROUP BY
        category,
        item_purchased
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM product_counts
WHERE product_rank <= 3
ORDER BY
    category,
    product_rank;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10. What is the revenue contribution of each age group? 
SELECT 
age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
